image: maven:latest

stages:
  - build
  - test

# variables:
#   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - .m2/repository/
    - target/

services:
  - docker:19.03.8-dind

before_script:
  - apt-get update -y 
  - apt-get upgrade -y 
  - apt-get install tightvncserver xfonts-base
            
  - docker info
  
#  - sudo usermod -aG docker gitlab-runner
#  - sudo -u gitlab-runner -H docker info
#  
#  - sudo apt-get update
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  
  - docker run hello-world
  
#  - sudo apt-get install \
#    apt-transport-https \
#    ca-certificates \
#    curl \
#    gnupg-agent \
#    software-properties-common
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo apt-key fingerprint 0EBFCD88
#  - sudo add-apt-repository \
#   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
#   $(lsb_release -cs) \
#   stable"
#   
#  - sudo apt-get install docker-ce docker-ce-cli containerd.io
  - docker info
#  - sudo docker run hello-world

build:
  stage: build
  script:

    - ./model/src/test/resources/docker/script/build.sh
    - ./model/src/test/resources/docker/script/run.sh
    - ./model/src/test/resources/docker/script/buff.sh
    - ./model/src/test/resources/docker/script/verify.sh   
    - mvn clean install -DskipTests

test:
  stage: test
  script:
    - mvn clean verify