language: java
services: docker
jdk: openjdk11

addons:
  sonarcloud:
    organization: "ron190-github"
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
before_install:
  
  - export MAVEN_OPTS="-Xms512m -Xmx3g -XX:PermSize=256m $MAVEN_OPTS"
    
  # Docker configuration
  - docker build -t mysql 
    -f src/test/resources/docker/Dockerfile.mysql .
    
  - docker build -t mysql 
    -f src/test/resources/docker/Dockerfile.mysql-5.5.40 .
    
  - docker build -t postgres 
    -f src/test/resources/docker/Dockerfile.postgres .
    
  - docker run --name jsql-mysql  
    --publish 3306:3306 
    -e MYSQL_ROOT_PASSWORD=my-secret-pw 
    -d mysql
    
  - docker run --name jsql-mysql-5.5.40 
    --publish 3307:3306 
    -e MYSQL_ROOT_PASSWORD=my-secret-pw 
    -d mysql:5.5.40
    
  - docker run --name jsql-postgres 
    --publish 5432:5432 
    -e POSTGRES_PASSWORD=mysecretpassword 
    -d postgres 
    -c 'shared_buffers=256MB'
    -c 'max_connections=1000'
    
  - docker images && docker ps && pwd

script:
  
  # Buff MySQL
  - docker exec -it jsql-mysql /bin/bash
    -c "
       mysql -uroot -pmy-secret-pw -e '
       SET GLOBAL max_connections = 100000;
       SET GLOBAL thread_cache_size = 16384;
       SET GLOBAL table_open_cache = 524288;
       ';
       "

  # Check MySQL status
  - docker exec -it jsql-mysql /bin/bash
    -c "
       mysql -uroot -pmy-secret-pw -e '
       SHOW GLOBAL variables WHERE Variable_name RLIKE \"thread_cache_size|^max_connections|table_open_cache\";
       SHOW GLOBAL status WHERE Variable_name RLIKE \"Threads_cached|Max_used_connections|Threads_created|Connections|Opened_tables|Threads_connected|Threads_running|^Queries\"
       ';
       "

  # Check Postgres status
  - docker exec -it jsql-postgres /bin/bash
    -c "
       export PGPASSWORD=mysecretpassword;
       psql -U postgres -h 127.0.0.1 -d \"\" -e -a -c '
       show max_connections;
       ';
       "

  - mvn clean verify sonar:sonar
  
  # Check MySQL status
  - docker exec -it jsql-mysql /bin/bash
    -c "
       mysql -uroot -pmy-secret-pw -e '
       SHOW GLOBAL status WHERE Variable_name RLIKE \"Threads_cached|Max_used_connections|Threads_created|Connections|Opened_tables|Threads_connected|Threads_running|^Queries\"
       ';
       "
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
