language: java
jdk: 
 # Keep concurrent jdk lower than Travis max job count of 5
 - openjdk8
 
before_install:

  - mvn -v
  - mvn -X dependency:tree
  - which mvn
  - find /usr -name '*jansi*' -exec ls -l {} \;
