language: java
services: docker
jdk: 
 - openjdk8
 - openjdk9
 - openjdk10
 - openjdk12
 - openjdk13
 # Keep concurrent jdk lower than Travis max job count of 5
 # - openjdk11
 # Need new version of gmavenplus-plugin
 # - openjdk14

addons:
  sonarcloud:
    organization: ron190-github
    token:
      secure: Fi8pYQTRDsIzBBKPTLHcAxkm0l0JcrZZvADbhwWG95lqKgtEtGI0OzWB5nFUBiOu5N20yrMPz/x4BUTyqr61xZiOocB9SH5ya4jqlraIlQW3WPH0enZ7e/g/JmqiAttuhzic7s12XQR5VwvAbG7ZkHa41liJ0nTd8HiLG7TOPep0hVTX/VZ/+K1B0FMJJVsMNMfhDsrtegxLryoeCSuKpwiAXXN2GkTtV2g1o1fxSmFMb0cepC/03Hskfp4ZxnHaY9yQfJISulTuxv9EUy5ecQZj+btf+QB3iNAwNFIE/xC6VeuCSrTJ01kG9w9DvY3W6z9NywxVHL5fJNDHcWsIz6/FpdNZgwxw6hIBQOimSa2/oXrPNyNR/bUyu6kQMFitDXWNxZj56yicqduNc46ni9NjsavCMlTJrdh/MYKB+C8e2IVa11QT988iTZo5C7MjUqUJU4gKBgdcn0jGZb20pxd7/Gtf4uMz7tp9mQRCTXpV6OSE85phwezledPud1f7/TG/QBrzZCL3YTMLhrDLhiratHweitPpr3da2+HrjSkdmunGdyufB+bseJP68ghjG5QpYBakjkJgkGYXd+S/r1NHmsGhbuk3/S0WtoYRhlAaBl3U8c7z8/lBcPhNbkQmfjIMolTjVdK61rQSads1b3kgVcImsux0IxEhUjowqag=

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
before_install:

  - sudo cat /proc/meminfo
  - java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
#  - export MAVEN_SKIP_RC=true
#  - export MAVEN_OPTS="-Xss512k -Xms2g -Xmx3g -Xmn3g -XX:PermSize=1g $MAVEN_OPTS"
#  - export MAVEN_OPTS="-Xss512k -Xms2g -Xmx3g -Xmn3g -XX:PermSize=1g $MAVEN_OPTS" > ~/.mavenrc
    
  # Docker configuration
  - ./src/test/resources/docker/script/build.sh
  - ./src/test/resources/docker/script/run.sh
  - ./src/test/resources/docker/script/verify.sh

script:

  - mvn clean verify sonar:sonar
  
  # Check MySQL status
  - docker exec -it jsql-mysql /bin/bash
    -c "
       mysql -uroot -pmy-secret-pw -e '
       SHOW GLOBAL status WHERE Variable_name RLIKE \"Threads_cached|Max_used_connections|Threads_created|Connections|Opened_tables|Threads_connected|Threads_running|^Queries\"
       ';
       "
    
after_success:

  - bash <(curl -s https://codecov.io/bash)
  
  - export CODACY_PROJECT_TOKEN=43e8b6719fbc4f3cbef25d863d7440c8
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
